[package]
name = "mtoken"
version = "0.1.0"
description = "mtoken is a simple token wrapper standard"
edition = "2021"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "lib"]
name = "mtoken"

[dependencies]
solana-program = "1.10.41"
anchor-lang = { version = "0.25.0", features = ["init-if-needed"] }
anchor-spl = "0.25.0"
spl-token = { version = "~3.3.1", features = ["no-entrypoint"] }
spl-associated-token-account = { version = "~1.0.5", features = ["no-entrypoint"] }
mpl-token-metadata = { version = "1.3.3", features = [ "no-entrypoint", ] }
arrayref = "0.3.6"
